#!/bin/sh

# Footgun-O-Matic 9000

rm -rf /var/cache/* /tmp/*
mkdir -p /var/cache/apk/
find "$1" \( -name ".gitignore" -o -name ".git" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name ".gitattributes" -o -name "*example*" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name "*.ico" -o -name "tests" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name "*.jpg" -o -name "*.jpeg" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*.h" -o -name "*.cpp" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*.c" -o -name "*README*" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*example*" -o -name "*.sample" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*.png" -o -name "*.gif" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*tutorial*" -o -name "Makefile" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*README*" -o -name "*.md" \) -prune -exec rm -f "{}" \;
find "$1" \( -name "*.log" -o -name "*.MD" \) -prune -exec rm -f "{}" \;
